#ifndef GLYPH_H
#define GLYPH_H

#define GLYPH_WIDTH 8
#define GLYPH_HEIGHT 8

/*******************************************************************/
/* Glyphs are rendered with OpenGL. An OpenGL library is required  */
/* to upload and render image data generated by InitialiseGlyph(). */
/*******************************************************************/
#include <SDL2/SDL_opengl.h>

/****************************************************/
/* Glyphs are stored in memory as Image structures. */
/****************************************************/
#include "image.h"

/**********************************************/
/* Loads the resources used to render glyphs. */
/**********************************************/
void InitialiseGlyph();
/**********************************************/
/* Frees the resources used to render glyphs. */
/**********************************************/
void CleanupGlyph();

void RenderGlyph(const char character, float x, float y, float w, float h);
void RenderString(const char *string, float x, float y, float w, float h);
#endif /* GLYPH_H */
